import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import TrailingCursor from "./Pages/Trailing";
import "./globals.css"; // Ensure this path is correct
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/sweecha.jpeg" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href={inter.href} />
      </Head>
      <body className={`font-sans ${inter.className}`}>
        <nav className="bg-green-500 text-white py-4">
          <div className="container mx-auto px-4">
            <div className="flex items-center justify-between">
              <div className="text-4xl font-semibold text-transparent bg-clip-text bg-gradient-to-r from-yellow-200 to-green-100 lg:text-6xl outline-1">
                I am Developer
              </div>
              <div className="flex gap-4 items-center">
                <Link href="/">Home</Link>
                <Link href="/">Projects</Link>
                <Link href="/">Education</Link>
                <Link href="/">Skills</Link>
                <Link href="/">Achievements</Link>
                <Link href="/">Contact Me</Link>
                <Link href="/">Certifications</Link>
                <Link href="/">AI Bootcamp Summary</Link>
              </div>
            </div>
          </div>
        </nav>
        <main>{children}</main>
        <footer className="bg-green-500 text-white py-4">
          <div className="container mx-auto px-4">
            <div className="text-center">Want to Contact Us?</div>
            <div className="flex justify-center gap-4 mt-2">
              <Link href="#">LinkedIn</Link>
              <Link href="#">Twitter</Link>
              <Link href="#">GitHub</Link>
            </div>
          </div>
        </footer>
        <TrailingCursor />
      </body>
    </html>
  );
};

export default RootLayout;
